---
instances:
- https://rsshub.ddns.net/
- https://rsshub.app/
routes:
- title: Linkedin - Google
  path: linkedin/company/google/posts
# baseUrl: https://raw.githubusercontent.com/masrafi115/proxy_rsshub/main # The Base Url Of xml folder
