---
instances:
- https://rss.shab.fun/
- https://vercel.getrss2021.xyz/
- https://rsshub.rssforever.com/
- http://getrss2021.xyz:1200/
- https://rsshub.app/
routes:
- title: Linkedin - Google
  path: linkedin/company/google/posts
# baseUrl: https://raw.githubusercontent.com/masrafi115/proxy_rsshub/main # The Base Url Of xml folder
